# Generated by Django 4.0.1 on 2022-03-12 07:30

from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.detail


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=150)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='NewsDetailView',
            fields=[
                ('categories_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.categories')),
            ],
            bases=('polls.categories', django.views.generic.detail.DetailView),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('text', models.TextField(max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='photos')),
                ('public', models.BooleanField(default=True)),
                ('aditional_category', models.ManyToManyField(blank=True, related_name='aditional', to='polls.Categories', verbose_name='Aditional Category')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main', to='polls.categories', verbose_name='Main Category')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
