# Generated by Django 4.0.1 on 2022-03-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=350, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(max_length=10000),
        ),
    ]
