# Generated by Django 4.0.1 on 2022-03-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_news_name_alter_news_slug_alter_news_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
